#All profiles
server:
  port: 8002
spring:
  profiles:
    active: prod
  datasource:
    driverClassName: org.h2.Driver
    username: test
    passwords: pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

api:
  default-values:
    pagination:
      rows: 10
      page: 0

---

# 'test' profile only
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
---

# 'prod' profile only
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:h2:mem:proddb